const values = {
    ADD_VALUE: "ADD_VALUE",
    REMOVE_VALUE: "REMOVE_VALUE",
    CLEAR_VALUE: "CLEAR_VALUE",
    ADD_DECIMAL: "ADD_DECIMAL",
    ADD_OPERATOR: "ADD_OPERATOR",
    EQUALS_OPERATOR: "EQUALS_OPERATOR",
    MAKE_NEGATIVE: "MAKE_NEGATIVE",
};

export default values;
